### ISSUE TITLE
Error in installing bartMan package

### ISSUE THREAD

**Issue by FrancoMagno19** [AlanInglis/bartMan#1]
Hi there,
First of all, thank you for your interesting contribution to the BART analysis, I found it really useful for the thesis I am carrying on BART application on IoT services' dataset.

Anyway, I am facing issues while trying to download 'bartMan' package. I did manage to install 'vivid' as you specified in the bartVisVignette.Rmd file, however, the software still cannot find any 'bartMan' package.
I am not the only one in facing that issue. 

Thank you for your time,
Francesco

**Comment by AlanInglis** [comment]
Hi Francesco. I am still in the process of updating the bartMan package and am writing a better, more detailed, vignette (which I hope to have pushed to GitHub today or tomorrow). There is a typo in the bartVisVignette.Rmd file. Currently, I am instructing you to download the vivid package (which is available on CRAN), when I should be instructing you to download the Bartman package. It should read:

devtools::install_github("AlanInglis/bartMan")

**Comment by FrancoMagno19** [comment]
The package is now available for download and ready to be used.
Thank you, Alan !!
