### ISSUE TITLE
Warning message: `stat(index)` was deprecated in ggplot2 3.4.0.

### ISSUE THREAD

**Issue by sreedta8** [AlanInglis/bartMan#2]
Hi Alan,

First my sincere thanks for creating a absolute gem of a visualization package for BART based output. The vignette you have provided is also among the best and the most comprehensive documents I have come across (given that it is a vignette). I have been using R for 17 years and so I mean it, when I say "your vignette made it so easy to understand how to accomplish various visualization tasks". Thank You!!!!!!!!

When I ran the following command: 

`vimpPlot(treeData = bmT, plotType = 'point')`

I got the following warning message:

Warning message:
`stat(index)` was deprecated in ggplot2 3.4.0.
Please use `after_stat(index)` instead.
The deprecated feature was likely used in the bartMan package.
Please report the issue to the authors.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 

Just posting this as an issue so you can address and eliminate the warning. Thanks once again for developing an awesome package to visualize BART models.

Sri

**Comment by AlanInglis** [comment]
Finally got around to fixing all the deprecated warnings.
