### ISSUE TITLE
getEdges function in plotAll.dbarts incorrect

### ISSUE THREAD

**Issue by DriWater** [AlanInglis/bartMan#4]
![tree_plots](https://github.com/AlanInglis/bartMan/assets/91761077/07949d6b-f95c-4d2f-a0ac-e5f170a2d28a)
When the tree depth grows, the getEdges function will sometimes unable to find the correct relationship between tree nodes, such as the example showing in this plot.  And I rewrite some part of the getEdges function in plotAll.dbarts and test it. I think this function now works when the tree structure is complex (in binary tree model). And this is my code:

`getEdges <- function(trees) {
  maxDepth <- trees$depthNEW[1]
  
  if (maxDepth > 2) {
    # Set the edge value:
    # this gets the 1st group of edges
    edgecnt <- data.frame(node = trees$node, edgenum = 2)
    edgecnt[trees$isLeaf, ]$edgenum <- 0
    
    edges <- NULL
    for(i in 2:nrow(edgecnt)){
      for(j in (i-1):1){
        if(edgecnt[j, ]$edgenum > 0){
          edges <- rbind(edges, c(edgecnt[j, ]$node, edgecnt[i, ]$node))
          edgecnt[j, ]$edgenum = edgecnt[j, ]$edgenum - 1
          break
        }
      }
    }
    
    edges <- data.frame(from = edges[,1], to =  edges[,2])
    
    # Change to right side of tree
    backToRoot <- edges %>%
      group_by(from) %>%
      filter(n() == 1)
    
    backToRoot$from <- 1
    edges <- rbind(edges, backToRoot)
    
    # remove duplicated rows and single row entries
    edges <- edges[!duplicated(edges), ]
    dups <- edges$from[duplicated(edges$from)]
    edges$unique <- edges$from %in% dups
    edgeIndex <- which(edges$unique == F)
    if (!length(edgeIndex) == 0) {
      edges <- edges[-edgeIndex, ]
    }
    drops <- c("unique")
    edges <- edges[, !(names(edges) %in% drops)]
    
    # reorder
    "edges" <- `row.names<-`(edges[with(edges, order(from, to)), ], NULL)
    edges <- edges[order(edges$to), ]
  } else {
    edges <- do.call(rbind, lapply(
      split(trees, ~ cumsum(!isLeaf)),
      function(x) {
        with(x, expand.grid(from = node[!isLeaf], to = node[isLeaf]))
      }
    ))
  }
}`

**Comment by AlanInglis** [comment]
Thanks for spotting that and thanks for providing a fix! I had a look at my code and spotted the mistake. And I have tested your code on a few situations where there is greater tree complexity. It seems to work well. So I have replaced the code (and added a small note thanking you).

**Comment by DriWater** [comment]
Thank you for making this fancy package. It is my pleasure.
